version: "3.9"
services:
  degu:
    image: vrvoyage/degudiffusion:1.0
    build: .
    env_file: .env
    environment:
      - STABLEDIFFUSION_CACHE_DIR=stablediffusion_cache
      - IMAGES_OUTPUT_DIRECTORY=generated # Can be commented if SAVE_IMAGES_TO_DISK is set to false
      # - SAVE_IMAGES_TO_DISK=false # If you uncomment this, you can comment the first volume
      # - STABLEDIFFUSION_MODE=fp16 # If you're low on VRAM
      # - STABLEDIFFUSION_MODEL_NAME=hakurei/waifu-diffusion # If you want to use Waifu Diffusion
    volumes:
      - ./generated:/app/generated # Only required if SAVE_IMAGES_TO_DISK=false isn't set
      - ./cache:/app/stablediffusion_cache # Related to STABLEDIFFUSION_CACHE_DIR
      - ./config:/app/config # Can be mounted in Read-Only if a 'replacers.json' file is already present
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

